import { createRequire } from "node:module";
import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { LruMap } from "@finesoft/core";
import type ts from "typescript";

export interface ControllerTypeOptions {
    /** Application root containing tsconfig.json. */
    root?: string;
    /** Alternate TypeScript config, resolved relative to root. */
    tsconfig?: string;
}
export interface ControllerTypeResult {
    readonly controllers: number;
    readonly changed: readonly string[];
}

const OUTPUT = ".finesoft/controller-types.d.ts";
const GENERATED = "// Generated by @finesoft/front. Edit route schemas, not this file.\n";
const PROBE = "__finesoftRouteInputProbe";
const moduleNames = new Set([
    "@finesoft/front",
    "@finesoft/front/web",
    "@finesoft/core",
    "@finesoft/web",
]);
interface Edit {
    start: number;
    end: number;
    text: string;
}
interface Registration {
    call: ts.CallExpression;
    controller: ts.ClassDeclaration;
}
interface ManagedController {
    node: ts.ClassDeclaration;
    key: string;
    name: string;
    inputs: string[];
}
interface TypeSnapshot {
    compiler: typeof ts;
    root: string;
    files: string[];
    stamp: string;
    stamps: Map<string, string>;
    hashes: Map<string, string>;
    output: string;
    content: string;
    replayable: boolean;
    result: ControllerTypeResult;
}
const cached = new Map<string, TypeSnapshot>();
const hash = (content: string | undefined) =>
    createHash("sha256")
        .update(content === undefined ? "missing" : `file:${content}`)
        .digest("hex");
// Keep only the latest application's graph, rather than retaining every one-shot build's ASTs.
let retained: { key: string; compiler: typeof ts; program: ts.Program } | undefined;
const slash = (value: string) => value.replaceAll("\\", "/");
const inside = (root: string, file: string) => {
    const relative = path.relative(root, file);
    return relative !== ".." && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative);
};
function assertEditablePath(root: string, file: string): void {
    let existing = file;
    while (!fs.existsSync(existing)) {
        if (fs.lstatSync(existing, { throwIfNoEntry: false }))
            throw Error(`Controller type generation cannot edit outside ${root}`);
        existing = path.dirname(existing);
    }
    if (!inside(root, fs.realpathSync(existing)))
        throw Error(`Controller type generation cannot edit outside ${root}`);
}
function applyEdits(source: string, edits: Edit[]): string {
    let boundary = source.length;
    for (const edit of edits.sort((a, b) => b.start - a.start)) {
        if (edit.end > boundary) throw Error("Overlapping controller type edits");
        source = source.slice(0, edit.start) + edit.text + source.slice(edit.end);
        boundary = edit.start;
    }
    return source;
}
function stamp(files: readonly string[]): string {
    return files
        .map((file) => {
            try {
                const stat = fs.statSync(file);
                return `${file}:${stat.mtimeMs}:${stat.size}`;
            } catch {
                return `${file}:missing`;
            }
        })
        .join("\n");
}

/** Generates type-only references; never imports or executes application modules. */
export function generateControllerTypes(options: ControllerTypeOptions = {}): ControllerTypeResult {
    return generateTypes(options);
}

function generateTypes(
    options: ControllerTypeOptions,
    observe?: (snapshot: TypeSnapshot) => void,
    force = false,
): ControllerTypeResult {
    const requestedRoot = path.resolve(options.root ?? process.cwd());
    const requestedConfig = path.resolve(requestedRoot, options.tsconfig ?? "tsconfig.json");
    if (!fs.existsSync(requestedConfig) || !fs.existsSync(path.join(requestedRoot, "src")))
        return { controllers: 0, changed: [] };
    const root = fs.realpathSync(requestedRoot);
    const configFile = fs.realpathSync(requestedConfig);
    const compiler = createRequire(path.join(root, "package.json"))("typescript") as typeof ts;
    const tokens = (source: string): string => {
        const scanner = compiler.createScanner(compiler.ScriptTarget.Latest, true);
        scanner.setText(source);
        const result: string[] = [];
        while (scanner.scan() !== compiler.SyntaxKind.EndOfFileToken)
            result.push(
                `${scanner.getToken()}:${scanner.getTokenValue() || scanner.getTokenText()}`,
            );
        return result.join("\n");
    };
    const configFiles = new Set([configFile]);
    const configContents = new Map<string, string | undefined>();
    const readConfig = (file: string) => {
        configFiles.add(file);
        const content = compiler.sys.readFile(file);
        configContents.set(file, content);
        return content;
    };
    const config = compiler.readConfigFile(configFile, readConfig);
    if (config.error)
        throw Error(compiler.flattenDiagnosticMessageText(config.error.messageText, "\n"));
    const parsed = compiler.parseJsonConfigFileContent(
        config.config,
        {
            ...compiler.sys,
            readFile: readConfig,
        },
        path.dirname(configFile),
    );
    if (parsed.errors.length)
        throw Error(
            parsed.errors
                .map((error) => compiler.flattenDiagnosticMessageText(error.messageText, "\n"))
                .join("\n"),
        );
    if (!parsed.fileNames.length && parsed.projectReferences?.length) {
        const projects: string[] = [];
        const seen = new Set<string>();
        const inspect = (reference: ts.ProjectReference): void => {
            const file = compiler.resolveProjectReferencePath(reference);
            if (seen.has(file)) return;
            seen.add(file);
            const project = compiler.getParsedCommandLineOfConfigFile(
                file,
                {},
                {
                    ...compiler.sys,
                    onUnRecoverableConfigFileDiagnostic: (error) => {
                        throw Error(compiler.flattenDiagnosticMessageText(error.messageText, "\n"));
                    },
                },
            );
            if (project?.fileNames.some((file) => inside(path.join(root, "src"), file)))
                projects.push(file);
            else project?.projectReferences?.forEach(inspect);
        };
        parsed.projectReferences.forEach(inspect);
        if (projects.length === 1)
            return generateTypes({ ...options, tsconfig: projects[0] }, observe, force);
        throw Error(
            "Select the application project with controllerTypes.tsconfig; the solution config must reference exactly one project containing src.",
        );
    }
    const cacheKey = `${root}#${configFile}`;
    const rootFiles = parsed.fileNames.filter((file) => inside(root, file));
    const previous = cached.get(cacheKey);
    const initialFiles = [
        ...new Set([...configFiles, ...rootFiles, ...(previous?.files ?? [])]),
    ].sort();
    const inputStamps = new Map(initialFiles.map((file) => [file, stamp([file])]));
    if (!force && previous && previous.stamp === [...inputStamps.values()].join("\n")) {
        observe?.(previous);
        return { ...previous.result, changed: [] };
    }
    const output = path.join(root, OUTPUT);
    const typeImports = (source: ts.SourceFile) =>
        source.statements.filter(
            (
                statement,
            ): statement is ts.ImportDeclaration & {
                importClause: ts.ImportClause & { namedBindings: ts.NamedImports };
            } =>
                compiler.isImportDeclaration(statement) &&
                compiler.isStringLiteral(statement.moduleSpecifier) &&
                path.resolve(path.dirname(source.fileName), statement.moduleSpecifier.text) ===
                    output.replace(/\.d\.ts$/, "") &&
                statement.importClause?.isTypeOnly === true &&
                !!statement.importClause.namedBindings &&
                compiler.isNamedImports(statement.importClause.namedBindings),
        );
    const typeImport = (type: ts.TypeNode): ts.ImportSpecifier | undefined => {
        if (!compiler.isTypeReferenceNode(type) || !compiler.isIdentifier(type.typeName)) return;
        let owner: ts.Node | undefined = type.parent;
        while (owner && !compiler.isClassDeclaration(owner)) owner = owner.parent;
        if (!owner?.name) return;
        const className = owner.name.text;
        const source = type.getSourceFile();
        const key = `${slash(path.relative(root, source.fileName))}#${className}`;
        const hash = createHash("sha256").update(key).digest("hex").slice(0, 12);
        const exports = ["Input", "Failure"].flatMap((suffix) => {
            const name = `${className}${suffix}`;
            return [name, `${name}_${hash}`];
        });
        return typeImports(source)
            .flatMap((statement) => statement.importClause.namedBindings.elements)
            .find(
                (element) =>
                    element.name.text === type.getText() &&
                    exports.includes((element.propertyName ?? element.name).text) &&
                    checker.getSymbolAtLocation(type.typeName) ===
                        checker.getSymbolAtLocation(element.name),
            );
    };
    const settings: ts.CompilerOptions = { ...parsed.options, noEmit: true, skipLibCheck: true };
    // Snapshot disk reads for the three analysis phases, never across separate saves.
    const memoize = <T>(read: (file: string) => T): ((file: string) => T) => {
        const values = new Map<string, T>();
        return (file) => {
            if (!values.has(file)) values.set(file, read(file));
            return values.get(file)!;
        };
    };
    const readFiles = new Set<string>();
    const readFile = memoize((file) => {
        readFiles.add(file);
        if (!inputStamps.has(file)) inputStamps.set(file, stamp([file]));
        return compiler.sys.readFile(file);
    });
    const fileExists = memoize(compiler.sys.fileExists.bind(compiler.sys));
    const directoryExists = memoize(compiler.sys.directoryExists.bind(compiler.sys));
    const realpath = compiler.sys.realpath && memoize(compiler.sys.realpath.bind(compiler.sys));
    const resolutions = compiler.createModuleResolutionCache(
        root,
        (file) => (compiler.sys.useCaseSensitiveFileNames ? file : file.toLowerCase()),
        settings,
    );
    let lastProgram =
        retained?.key === cacheKey && retained.compiler === compiler ? retained.program : undefined;
    let firstPhase = true;
    const programFiles = [...rootFiles, output];
    const buildProgram = (
        options: ts.CompilerOptions,
        overrides = new Map<string, string>(),
    ): ts.Program => {
        const host = compiler.createCompilerHost(options);
        const getSourceFile = host.getSourceFile.bind(host);
        let previous = lastProgram;
        host.readFile = (file) => overrides.get(file) ?? readFile(file);
        host.fileExists = (file) => overrides.has(file) || fileExists(file);
        host.directoryExists = (directory) =>
            (directory === path.dirname(output) && overrides.has(output)) ||
            directoryExists(directory);
        host.realpath = realpath;
        // The declaration can first appear virtually during a cold generation.
        if (overrides.has(output) && !lastProgram?.getSourceFile(output)) resolutions.clear();
        host.getModuleResolutionCache = () => resolutions;
        host.resolveModuleNameLiterals = (imports, file, redirected, options, source) =>
            imports.map((specifier) =>
                compiler.resolveModuleName(
                    specifier.text,
                    file,
                    options,
                    host,
                    resolutions,
                    redirected,
                    compiler.getModeForUsageLocation(source, specifier, options),
                ),
            );
        // Refresh external changes once per save; subsequent phases share that disk snapshot.
        const refreshResolutions = firstPhase;
        firstPhase = false;
        host.hasInvalidatedResolutions = () => refreshResolutions;
        host.getSourceFile = (file, language, onError, fresh) => {
            const source = previous?.getSourceFile(file);
            const target = typeof language === "number" ? language : language.languageVersion;
            const format = typeof language === "number" ? undefined : language.impliedNodeFormat;
            if (
                !fresh &&
                source &&
                source.languageVersion === target &&
                source.impliedNodeFormat === format &&
                source.text === host.readFile(file)
            )
                return source;
            return getSourceFile(file, language, onError, fresh);
        };
        try {
            return (lastProgram = compiler.createProgram(programFiles, options, host, previous));
        } finally {
            // The new program owns this host: do not keep a chain of previous programs alive.
            previous = undefined;
        }
    };
    const sourceProgram = buildProgram(settings);
    const syntaxErrors = sourceProgram.getSyntacticDiagnostics();
    if (syntaxErrors.length)
        throw Error(
            `Fix source syntax before generating controller types: ${syntaxErrors.map((error) => `${error.file?.fileName}: ${compiler.flattenDiagnosticMessageText(error.messageText, "\n")}`).join("\n")}`,
        );
    const checker = sourceProgram.getTypeChecker();
    const resolve = (symbol: ts.Symbol | undefined): ts.Symbol | undefined =>
        symbol &&
        (symbol.flags & compiler.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol);
    const definitions = new Set<ts.Symbol>();
    const bases = new Set<ts.Symbol>();
    for (const source of sourceProgram.getSourceFiles()) {
        if (!inside(root, source.fileName) || source.isDeclarationFile) continue;
        for (const statement of source.statements) {
            if (
                !compiler.isImportDeclaration(statement) ||
                !compiler.isStringLiteral(statement.moduleSpecifier) ||
                !moduleNames.has(statement.moduleSpecifier.text)
            )
                continue;
            const symbol = checker.getSymbolAtLocation(statement.moduleSpecifier);
            if (!symbol) continue;
            for (const exported of checker.getExportsOfModule(symbol)) {
                const resolved = resolve(exported);
                if (resolved && exported.name === "definePage") definitions.add(resolved);
                if (resolved && exported.name === "BaseController") bases.add(resolved);
            }
        }
    }
    const registrations: Registration[] = [];
    const classes: ts.ClassDeclaration[] = [];
    const visit = (node: ts.Node): void => {
        if (compiler.isClassDeclaration(node) && node.name) {
            const base = node.heritageClauses?.find(
                (clause) => clause.token === compiler.SyntaxKind.ExtendsKeyword,
            )?.types[0];
            if (base && bases.has(resolve(checker.getSymbolAtLocation(base.expression))!))
                classes.push(node);
        }
        if (
            compiler.isCallExpression(node) &&
            definitions.has(resolve(checker.getSymbolAtLocation(node.expression))!) &&
            node.arguments[0]
        ) {
            const input = checker.getTypeAtLocation(node.arguments[0]);
            const routes = input.getProperty("routes");
            const create = input.getProperty("create");
            if (routes && create) {
                const factory = checker.getTypeOfSymbolAtLocation(create, node);
                for (const signature of factory.getCallSignatures()) {
                    const result = signature.getReturnType();
                    for (const type of result.isUnion() ? result.types : [result]) {
                        const declaration = type.getSymbol()?.valueDeclaration;
                        if (
                            !declaration ||
                            !compiler.isClassDeclaration(declaration) ||
                            !declaration.name
                        )
                            continue;
                        const base = declaration.heritageClauses?.find(
                            (clause) => clause.token === compiler.SyntaxKind.ExtendsKeyword,
                        )?.types[0];
                        if (
                            !base ||
                            !bases.has(resolve(checker.getSymbolAtLocation(base.expression))!)
                        )
                            continue;
                        if (!inside(root, declaration.getSourceFile().fileName))
                            throw Error(`Controller type generation cannot edit outside ${root}`);
                        registrations.push({ call: node, controller: declaration });
                    }
                }
            }
        }
        compiler.forEachChild(node, visit);
    };
    for (const source of sourceProgram.getSourceFiles())
        if (
            inside(root, source.fileName) &&
            !source.isDeclarationFile &&
            !source.fileName.includes(`${path.sep}node_modules${path.sep}`)
        )
            visit(source);

    const virtual = new Map<string, string>();
    const calls = new Map<string, Set<number>>();
    for (const { call } of registrations) {
        const file = call.getSourceFile().fileName;
        let positions = calls.get(file);
        if (!positions) calls.set(file, (positions = new Set()));
        positions.add(call.expression.getStart());
    }
    for (const [file, positions] of calls) {
        const source = sourceProgram.getSourceFile(file)!;
        const edits: Edit[] = [];
        const replace = (node: ts.Node): void => {
            if (compiler.isCallExpression(node) && positions.has(node.expression.getStart()))
                edits.push({
                    start: node.expression.getStart(),
                    end: node.expression.end,
                    text: PROBE,
                });
            compiler.forEachChild(node, replace);
        };
        replace(source);
        virtual.set(
            file,
            applyEdits(source.text, edits) +
                `\ndeclare function ${PROBE}<const R extends readonly (string | import("@finesoft/front/web").PageRoute)[]>(input: { routes: R; [key: string]: unknown }): import("@finesoft/front/web").RouteInputFor<R>;\n`,
        );
    }
    virtual.set(output, "export {};\n");
    const program = buildProgram(settings, virtual);
    const types = program.getTypeChecker();
    const inferred = new Map<string, ts.Type[]>();
    for (const [file] of calls) {
        const found: ts.Type[] = [];
        const collect = (node: ts.Node): void => {
            if (
                compiler.isCallExpression(node) &&
                compiler.isIdentifier(node.expression) &&
                node.expression.text === PROBE
            )
                found.push(types.getTypeAtLocation(node));
            compiler.forEachChild(node, collect);
        };
        collect(program.getSourceFile(file)!);
        inferred.set(file, found);
    }
    const byCall = new Map<ts.CallExpression, ts.Type>();
    for (const [file] of calls) {
        const originals = [
            ...new Set(
                registrations
                    .filter((entry) => entry.call.getSourceFile().fileName === file)
                    .map((entry) => entry.call),
            ),
        ];
        originals.forEach((call, index) => byCall.set(call, inferred.get(file)![index]));
    }
    const printer = compiler.createPrinter();
    const outputSource = program.getSourceFile(output)!;
    const factory = compiler.factory;
    const schemaOutputs = new Map<ts.Type, ts.TypeNode>();
    let schemaOutputsReady = false;
    const propertyType = (type: ts.Type, key: string, location: ts.Node): ts.Type | undefined => {
        const property = types.getNonNullableType(type).getProperty(key);
        return property && types.getTypeOfSymbolAtLocation(property, location);
    };
    const schemaOutput = (type: ts.Type): ts.TypeNode | undefined => {
        if (!(type.flags & (compiler.TypeFlags.Object | compiler.TypeFlags.Intersection))) return;
        // Primitive inputs need no export scan. Resolve accessible schemas only for object outputs.
        if (!schemaOutputsReady) {
            schemaOutputsReady = true;
            // Reference an accessible schema when its output is nominal or cannot be named outside its module.
            for (const source of program.getSourceFiles()) {
                const symbol = types.getSymbolAtLocation(source);
                if (!symbol || source.fileName === output) continue;
                for (const exported of types.getExportsOfModule(symbol)) {
                    const type = types.getTypeOfSymbolAtLocation(exported, source);
                    const signatures = type.getCallSignatures();
                    const schema = signatures.length ? signatures[0].getReturnType() : type;
                    const standard = propertyType(schema, "~standard", source);
                    const metadata = standard && propertyType(standard, "types", source);
                    const result = metadata && propertyType(metadata, "output", source);
                    if (
                        !result ||
                        !(
                            result.flags &
                            (compiler.TypeFlags.Object | compiler.TypeFlags.Intersection)
                        )
                    )
                        continue;
                    let modulePath = slash(
                        path.relative(path.dirname(output), source.fileName),
                    ).replace(/(\.d)?\.([cm]?)tsx?$/, ".$2js");
                    if (!modulePath.startsWith(".")) modulePath = `./${modulePath}`;
                    const reference = factory.createImportTypeNode(
                        factory.createLiteralTypeNode(factory.createStringLiteral(modulePath)),
                        undefined,
                        factory.createIdentifier(exported.name),
                        undefined,
                        true,
                    );
                    const schemaReference = signatures.length
                        ? factory.createTypeReferenceNode("ReturnType", [reference])
                        : reference;
                    schemaOutputs.set(
                        result,
                        factory.createImportTypeNode(
                            factory.createLiteralTypeNode(
                                factory.createStringLiteral("@finesoft/front"),
                            ),
                            undefined,
                            factory.createIdentifier("InferOutput"),
                            [schemaReference],
                        ),
                    );
                }
            }
        }
        return schemaOutputs.get(type);
    };
    const buildTypeNode = (type: ts.Type, depth = 0): ts.TypeNode => {
        // RouteInput and its params/query maps are synthetic; schemas describe their field values.
        const schema = depth >= 2 ? schemaOutput(type) : undefined;
        if (schema) return schema;
        if (type.isUnion())
            return factory.createUnionTypeNode(
                type.types.map((value) => buildTypeNode(value, depth)),
            );
        const node = types.typeToTypeNode(
            type,
            outputSource,
            compiler.NodeBuilderFlags.NoTruncation |
                compiler.NodeBuilderFlags.UseFullyQualifiedType |
                compiler.NodeBuilderFlags.InTypeAlias,
        );
        if (!node) throw Error("Cannot serialize inferred controller input");
        if (!compiler.isTypeLiteralNode(node)) return node;
        return factory.updateTypeLiteralNode(
            node,
            factory.createNodeArray(
                node.members.map((member) => {
                    if (
                        !compiler.isPropertySignature(member) ||
                        !member.type ||
                        !(
                            compiler.isIdentifier(member.name) ||
                            compiler.isStringLiteral(member.name)
                        )
                    )
                        return member;
                    const value = propertyType(type, member.name.text, outputSource);
                    return value
                        ? factory.updatePropertySignature(
                              member,
                              member.modifiers,
                              member.name,
                              member.questionToken,
                              buildTypeNode(value, depth + 1),
                          )
                        : member;
                }),
            ),
        );
    };
    const printType = (type: ts.Type): string => {
        if (!type || type.flags & (compiler.TypeFlags.Any | compiler.TypeFlags.Unknown))
            throw Error(
                "Cannot infer controller input. Check route schemas and @finesoft/front/web types.",
            );
        const node = buildTypeNode(type);
        const rejectAny = (value: ts.Node): void => {
            if (value.kind === compiler.SyntaxKind.AnyKeyword)
                throw Error(
                    "Cannot generate an any controller input. Check route schemas and their imports.",
                );
            compiler.forEachChild(value, rejectAny);
        };
        rejectAny(node);
        const transformed = compiler.transform(node, [
            (context) => {
                const visitType = (value: ts.Node): ts.VisitResult<ts.Node> => {
                    if (
                        compiler.isImportTypeNode(value) &&
                        compiler.isLiteralTypeNode(value.argument) &&
                        compiler.isStringLiteral(value.argument.literal) &&
                        path.isAbsolute(value.argument.literal.text)
                    ) {
                        let relative = slash(
                            path.relative(path.dirname(output), value.argument.literal.text),
                        );
                        if (!relative.startsWith(".")) relative = `./${relative}`;
                        return context.factory.updateImportTypeNode(
                            value,
                            context.factory.createLiteralTypeNode(
                                context.factory.createStringLiteral(relative),
                            ),
                            value.attributes,
                            value.qualifier,
                            value.typeArguments,
                            value.isTypeOf,
                        );
                    }
                    return compiler.visitEachChild(value, visitType, context);
                };
                return (node) => compiler.visitNode(node, visitType) as ts.TypeNode;
            },
        ]);
        try {
            return printer.printNode(
                compiler.EmitHint.Unspecified,
                transformed.transformed[0],
                outputSource,
            );
        } finally {
            transformed.dispose();
        }
    };
    const managed = new Map<ts.ClassDeclaration, ManagedController>();
    for (const { call, controller } of registrations) {
        const file = controller.getSourceFile();
        const methods = controller.members.filter(
            (member): member is ts.MethodDeclaration =>
                compiler.isMethodDeclaration(member) &&
                compiler.isIdentifier(member.name) &&
                ["execute", "fallback"].includes(member.name.text),
        );
        if (
            !methods.some((method) =>
                method.parameters.some(
                    (parameter) => !parameter.type || typeImport(parameter.type),
                ),
            )
        )
            continue;
        const name = controller.name!.text;
        let entry = managed.get(controller);
        if (!entry)
            managed.set(
                controller,
                (entry = {
                    node: controller,
                    key: `${slash(path.relative(root, file.fileName))}#${name}`,
                    name,
                    inputs: [],
                }),
            );
        entry.inputs.push(printType(byCall.get(call)!));
    }
    const saved = fs.existsSync(output) ? fs.readFileSync(output, "utf8") : "";
    let replayable = true;
    if (saved.startsWith(GENERATED)) {
        const previous = compiler.createSourceFile(
            output,
            saved,
            compiler.ScriptTarget.Latest,
            true,
        );
        const inputs = new Map<string, string>();
        for (const statement of previous.statements)
            if (
                compiler.isInterfaceDeclaration(statement) &&
                statement.name.text === "ControllerInputs"
            )
                for (const member of statement.members)
                    if (
                        compiler.isPropertySignature(member) &&
                        compiler.isStringLiteral(member.name) &&
                        member.type
                    )
                        inputs.set(member.name.text, member.type.getText(previous));
        // An unregistered class may still be used independently. Keep its last known contract.
        for (const controller of classes) {
            if (managed.has(controller)) continue;
            const source = controller.getSourceFile();
            const name = controller.name!.text;
            const key = `${slash(path.relative(root, source.fileName))}#${name}`;
            if (
                inputs.has(key) &&
                controller.members.some(
                    (member) =>
                        compiler.isMethodDeclaration(member) &&
                        member.parameters.some(
                            (parameter) => parameter.type && typeImport(parameter.type),
                        ),
                )
            ) {
                replayable = false;
                managed.set(controller, {
                    node: controller,
                    key,
                    name,
                    inputs: [inputs.get(key)!],
                });
            }
        }
    }
    const updates = new Map<string, string>();
    const sourceEdits = new Map<ts.SourceFile, Edit[]>();
    const aliases = new Map<ts.SourceFile, string[]>();
    const names = new Map<string, number>();
    for (const entry of managed.values()) names.set(entry.name, (names.get(entry.name) ?? 0) + 1);
    const exportedName = (entry: ManagedController, suffix = "Input") =>
        `${entry.name}${suffix}${
            names.get(entry.name)! > 1
                ? `_${createHash("sha256").update(entry.key).digest("hex").slice(0, 12)}`
                : ""
        }`;
    const modulePaths = new Map<ts.SourceFile, string>();
    const localNames = new Map<ts.SourceFile, Set<string>>();
    const fileCounts = new Map<ts.SourceFile, number>();
    const ownedImports = new Set<ts.ImportSpecifier>();
    for (const entry of managed.values()) {
        const annotations = entry.node.members.flatMap((member) =>
            compiler.isMethodDeclaration(member) &&
            compiler.isIdentifier(member.name) &&
            ["execute", "fallback"].includes(member.name.text)
                ? member.parameters.flatMap((parameter) => (parameter.type ? [parameter.type] : []))
                : [],
        );
        for (const clause of entry.node.heritageClauses ?? [])
            if (clause.token === compiler.SyntaxKind.ExtendsKeyword)
                annotations.push(...(clause.types[0].typeArguments?.slice(0, 1) ?? []));
        for (const type of annotations) {
            const imported = typeImport(type);
            if (imported) ownedImports.add(imported);
        }
    }
    for (const entry of managed.values()) {
        const source = entry.node.getSourceFile();
        fileCounts.set(source, (fileCounts.get(source) ?? 0) + 1);
        if (localNames.has(source)) continue;
        const imported = new Set(
            typeImports(source).flatMap((statement) =>
                statement.importClause.namedBindings.elements
                    .filter((element) => ownedImports.has(element))
                    .map((element) => element.name.text),
            ),
        );
        const used = new Set<string>();
        const visit = (node: ts.Node): void => {
            if (compiler.isIdentifier(node) && !imported.has(node.text)) used.add(node.text);
            compiler.forEachChild(node, visit);
        };
        visit(source);
        localNames.set(source, used);
    }
    for (const entry of managed.values()) {
        const source = entry.node.getSourceFile();
        let edits = sourceEdits.get(source);
        if (!edits) sourceEdits.set(source, (edits = []));
        const imports = typeImports(source).flatMap(
            (statement) => statement.importClause.namedBindings.elements,
        );
        const alias = (suffix: string): string => {
            const used = localNames.get(source)!;
            const exported = `${entry.name}${suffix}`;
            const existing = imports.find((element) => {
                const name = (element.propertyName ?? element.name).text;
                return (
                    ownedImports.has(element) &&
                    (name === exported ||
                        (name.startsWith(exported) &&
                            /^_[a-f0-9]{12}$/.test(name.slice(exported.length))))
                );
            });
            const preferred =
                existing?.name.text ?? (fileCounts.get(source) === 1 ? suffix : exported);
            let name = preferred;
            if (used.has(name)) name = `${entry.name}${suffix}`;
            for (let i = 2; used.has(name); i++) name = `${entry.name}${suffix}${i}`;
            used.add(name);
            return name;
        };
        const parameterType = alias("Input");
        const failureType = alias("Failure");
        let modulePath = slash(path.relative(path.dirname(source.fileName), output)).replace(
            /\.d\.ts$/,
            "",
        );
        if (!modulePath.startsWith(".")) modulePath = `./${modulePath}`;
        const list = aliases.get(source) ?? [];
        const importAs = (suffix: string, local: string) => {
            const name = exportedName(entry, suffix);
            list.push(name === local ? name : `${name} as ${local}`);
        };
        importAs("Input", parameterType);
        aliases.set(source, list);
        modulePaths.set(source, modulePath);
        for (const member of entry.node.members) {
            if (
                !compiler.isMethodDeclaration(member) ||
                !compiler.isIdentifier(member.name) ||
                !["execute", "fallback"].includes(member.name.text)
            )
                continue;
            if (member.parameters.length > 1)
                throw Error(
                    `Use ${member.name.text}({ params, query, context${member.name.text === "fallback" ? ", error" : ""} }) in ${source.fileName}`,
                );
            const parameter = member.parameters[0];
            if (!parameter || (parameter.type && !typeImport(parameter.type))) continue;
            const desired = member.name.text === "execute" ? parameterType : failureType;
            if (member.name.text === "fallback") importAs("Failure", failureType);
            edits.push(
                parameter.type
                    ? {
                          start: parameter.type.getStart(),
                          end: parameter.type.end,
                          text: desired,
                      }
                    : {
                          start: parameter.questionToken?.end ?? parameter.name.end,
                          end: parameter.questionToken?.end ?? parameter.name.end,
                          text: `: ${desired}`,
                      },
            );
        }
        const base = entry.node.heritageClauses!.find(
            (clause) => clause.token === compiler.SyntaxKind.ExtendsKeyword,
        )!.types[0];
        const execute = entry.node.members.find(
            (member): member is ts.MethodDeclaration =>
                compiler.isMethodDeclaration(member) &&
                compiler.isIdentifier(member.name) &&
                member.name.text === "execute",
        );
        let result = 'import("@finesoft/front/web").BasePage';
        if (execute?.type) {
            const type = checker.getTypeAtLocation(execute.type);
            const awaited = checker.getAwaitedType(type);
            result =
                awaited === type ? execute.type.getText() : `Awaited<${execute.type.getText()}>`;
            if (
                compiler.isTypeReferenceNode(execute.type) &&
                execute.type.typeName.getText() === "Promise" &&
                execute.type.typeArguments?.length === 1
            ) {
                const value = execute.type.typeArguments[0];
                if (checker.getTypeAtLocation(value) === awaited) result = value.getText();
            }
        }
        const argumentsText = `<${parameterType}, ${result}>`;
        if (
            (!base.typeArguments?.length || typeImport(base.typeArguments[0])) &&
            tokens(source.text.slice(base.expression.end, base.end)) !== tokens(argumentsText)
        )
            edits.push({
                start: base.expression.end,
                end: base.end,
                text: argumentsText,
            });
    }
    for (const [source, edits] of sourceEdits) {
        const imports = typeImports(source);
        const specifiers = [
            ...aliases.get(source)!,
            ...imports.flatMap((statement) =>
                statement.importClause.namedBindings.elements
                    .filter((element) => !ownedImports.has(element))
                    .map((element) => element.getText()),
            ),
        ];
        const desired = [...new Set(specifiers)].sort();
        const declaration = `import type { ${desired.join(", ")} } from ${JSON.stringify(modulePaths.get(source))};`;
        if (imports.length) {
            const [first, ...rest] = imports;
            const existing = first.importClause.namedBindings.elements
                .map((element) => tokens(element.getText()))
                .sort();
            if (existing.join("\n") !== desired.map(tokens).sort().join("\n"))
                edits.push({ start: first.getStart(), end: first.end, text: declaration });
            for (const statement of rest)
                edits.push({ start: statement.getStart(), end: statement.end, text: "" });
        } else {
            const position =
                source.statements.filter(compiler.isImportDeclaration).at(-1)?.end ??
                source.statements[0]?.getStart() ??
                source.end;
            edits.push({ start: position, end: position, text: `\n${declaration}\n` });
        }
        updates.set(source.fileName, applyEdits(source.text, edits));
    }
    if (managed.size || fs.existsSync(output)) {
        if (fs.existsSync(output) && !fs.readFileSync(output, "utf8").startsWith(GENERATED))
            throw Error(`Refusing to overwrite unowned controller declarations: ${output}`);
        updates.set(
            output,
            `${GENERATED}export interface ControllerInputs {\n${[...managed.values()]
                .sort((a, b) => a.key.localeCompare(b.key))
                .map(
                    (entry) =>
                        `    ${JSON.stringify(entry.key)}: ${[...new Set(entry.inputs)].join(" | ")};`,
                )
                .join("\n")}\n}\n${[...managed.values()]
                .sort((a, b) => a.key.localeCompare(b.key))
                .map(
                    (entry) =>
                        `export type ${exportedName(entry)} = ControllerInputs[${JSON.stringify(entry.key)}] & { readonly context: import("@finesoft/front").ExecutionContext };\nexport type ${exportedName(entry, "Failure")} = ${exportedName(entry)} & { readonly error: Error };`,
                )
                .join("\n")}\n`,
        );
    }
    if (updates.has(output)) {
        const validationOptions = { ...settings, skipLibCheck: false };
        const validation = buildProgram(validationOptions, updates);
        const generated = validation.getSourceFile(output)!;
        const errors = [
            ...validation.getSyntacticDiagnostics(generated),
            ...validation.getSemanticDiagnostics(generated),
        ];
        if (errors.length)
            throw Error(
                `Cannot generate controller declarations:\n${compiler.formatDiagnosticsWithColorAndContext(
                    errors,
                    {
                        getCanonicalFileName: (file) => file,
                        getCurrentDirectory: () => root,
                        getNewLine: () => "\n",
                    },
                )}`,
            );
    }
    for (const [source] of sourceEdits)
        if (fs.readFileSync(source.fileName, "utf8") !== source.text)
            throw Error(`Controller changed during type generation: ${source.fileName}`);
    for (const file of updates.keys()) assertEditablePath(root, file);
    const changed: string[] = [];
    for (const [file, content] of updates) {
        if (fs.existsSync(file)) {
            const existing = fs.readFileSync(file, "utf8");
            if (file === output ? tokens(existing) === tokens(content) : existing === content)
                continue;
        }
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, content);
        inputStamps.set(file, stamp([file]));
        changed.push(file);
    }
    const files = [
        ...new Set([
            ...configFiles,
            ...rootFiles,
            output,
            // Package metadata participates in resolution just as source text does.
            ...readFiles,
        ]),
    ].sort();
    const result = { controllers: managed.size, changed };
    // Cache the inputs we read, not a later save that arrived while we were generating.
    const hashes = new Map<string, string>();
    for (const file of files) {
        if (file === output) continue;
        const unchanged = !force && inputStamps.get(file) === previous?.stamps.get(file);
        hashes.set(
            file,
            (unchanged && previous?.hashes.get(file)) ||
                hash(configContents.get(file) ?? updates.get(file) ?? readFile(file)),
        );
    }
    const snapshot: TypeSnapshot = {
        compiler,
        root,
        files,
        stamp: files.map((file) => inputStamps.get(file) ?? stamp([file])).join("\n"),
        stamps: inputStamps,
        hashes,
        output,
        content: changed.includes(output) ? updates.get(output)! : saved,
        replayable,
        result,
    };
    cached.set(cacheKey, snapshot);
    retained = { key: cacheKey, compiler, program: lastProgram! };
    observe?.(snapshot);
    return result;
}

/** Watch events are the invalidation source; one-shot calls still inspect the complete project. */
export function createControllerTypeWatcher(options: ControllerTypeOptions) {
    let snapshot: TypeSnapshot | undefined;
    let onChange: ((file: string) => void) | undefined;
    const subscriptions = new Map<string, ts.FileWatcher>();
    const directories = new Map<string, ts.FileWatcher>();
    const versions = new LruMap<string, { content: string; controllers: number }>(8);
    const key = (hashes: Map<string, string>) => hash([...hashes.values()].join(""));
    const subscribe = () => {
        if (!onChange || !snapshot) return;
        const { compiler, hashes } = snapshot;
        if (!compiler.sys.watchFile || !compiler.sys.watchDirectory)
            throw Error("TypeScript file watching is unavailable");
        for (const [file, subscription] of subscriptions) {
            if (hashes.has(file)) continue;
            subscription.close();
            subscriptions.delete(file);
        }
        for (const file of hashes.keys())
            if (!subscriptions.has(file))
                subscriptions.set(
                    file,
                    compiler.sys.watchFile(file, () => onChange?.(file), 250, {
                        // Watch editable app files directly; share parent watchers for dependencies.
                        watchFile:
                            inside(snapshot.root, file) && !slash(file).includes("/node_modules/")
                                ? compiler.WatchFileKind.UseFsEvents
                                : compiler.WatchFileKind.UseFsEventsOnParentDirectory,
                        fallbackPolling: compiler.PollingWatchKind.PriorityInterval,
                        synchronousWatchDirectory: true,
                    }),
                );
        // New files can replace a resolved module, even in directories Vite ignores.
        const desired = new Set<string>();
        for (const file of hashes.keys()) {
            const directory = path.dirname(file);
            if (inside(snapshot.root, directory) && !slash(file).includes("/node_modules/"))
                continue;
            desired.add(directory);
            desired.add(path.dirname(directory));
        }
        for (const [directory, subscription] of directories) {
            if (desired.has(directory)) continue;
            subscription.close();
            directories.delete(directory);
        }
        for (const directory of desired)
            if (!directories.has(directory))
                directories.set(
                    directory,
                    compiler.sys.watchDirectory(
                        directory,
                        (file) => {
                            if (!snapshot?.hashes.has(file)) onChange?.(file);
                        },
                        false,
                        {
                            watchDirectory: compiler.WatchDirectoryKind.UseFsEvents,
                            synchronousWatchDirectory: true,
                        },
                    ),
                );
    };
    const generate = (force: boolean) => {
        const result = generateTypes(
            options,
            (next) => {
                if (snapshot?.files.join("\n") !== next.files.join("\n")) versions.clear();
                snapshot = next;
                subscribe();
                if (!next.replayable) {
                    versions.clear();
                    return;
                }
                const fingerprint = key(next.hashes);
                versions.set(fingerprint, {
                    content: next.content,
                    controllers: next.result.controllers,
                });
            },
            force,
        );
        return { ...result, cache: "generated" as const };
    };
    generate(false);
    return {
        watch(listener: (file: string) => void) {
            onChange = listener;
            subscribe();
            // Close the interval between taking the initial snapshot and attaching watchers.
            if (snapshot)
                for (const file of snapshot.hashes.keys())
                    if (stamp([file]) !== snapshot.stamps.get(file)) onChange(file);
        },
        update(files: readonly string[], cachedOnly = false) {
            if (!snapshot) return cachedOnly ? undefined : generate(true);
            if (snapshot.content && !fs.existsSync(snapshot.output))
                return cachedOnly ? undefined : generate(true);
            const hashes = new Map(snapshot.hashes);
            let changed = false;
            for (const file of files) {
                // New/deleted files and resolution metadata may change the project graph.
                if (!hashes.has(file) || file.endsWith(".json") || !fs.existsSync(file)) {
                    versions.clear();
                    return cachedOnly ? undefined : generate(true);
                }
                const next = hash(fs.readFileSync(file, "utf8"));
                changed ||= next !== hashes.get(file);
                hashes.set(file, next);
            }
            if (!changed) return { ...snapshot.result, changed: [], cache: "unchanged" as const };
            const fingerprint = key(hashes);
            const known = versions.get(fingerprint);
            if (!known) return cachedOnly ? undefined : generate(true);
            const exists = fs.existsSync(snapshot.output);
            const existing = exists ? fs.readFileSync(snapshot.output, "utf8") : "";
            if (exists && !existing.startsWith(GENERATED))
                throw Error(
                    `Refusing to overwrite unowned controller declarations: ${snapshot.output}`,
                );
            const written: string[] = [];
            if (existing !== known.content) {
                assertEditablePath(snapshot.root, snapshot.output);
                fs.mkdirSync(path.dirname(snapshot.output), { recursive: true });
                fs.writeFileSync(snapshot.output, known.content);
                written.push(snapshot.output);
            }
            const result = { controllers: known.controllers, changed: written };
            snapshot = { ...snapshot, hashes, content: known.content, result };
            return { ...result, cache: "reused" as const };
        },
        close() {
            onChange = undefined;
            for (const subscription of subscriptions.values()) subscription.close();
            for (const subscription of directories.values()) subscription.close();
            subscriptions.clear();
            directories.clear();
            snapshot = undefined;
            versions.clear();
            releaseControllerTypes(options.root ?? process.cwd());
        },
    };
}

/** Release development-only compiler state when its host closes. */
export function releaseControllerTypes(root: string): void {
    const prefix = `${fs.existsSync(root) ? fs.realpathSync(root) : path.resolve(root)}#`;
    for (const key of cached.keys()) if (key.startsWith(prefix)) cached.delete(key);
    if (retained?.key.startsWith(prefix)) retained = undefined;
}
