import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import type ts from "typescript";
import { assertEditablePath } from "./controller-types";

export interface FrontTypeOptions {
    /** Project directory; defaults to the current working directory. */
    root?: string;
    /** Project tsconfig, relative to root. Existing options and comments are preserved. */
    tsconfig?: string;
}

const slash = (value: string) => value.replaceAll("\\", "/");
const relative = (from: string, to: string) => {
    const name = slash(path.relative(from, to));
    return name.startsWith("./") || name.startsWith("../") ? name : `./${name}`;
};

/** Maintain an exact root alias with only the project's installed platform/native contracts. */
export function generateFrontTypes(options: FrontTypeOptions = {}): readonly string[] {
    const requestedRoot = path.resolve(options.root ?? process.cwd());
    const requestedConfig = path.resolve(requestedRoot, options.tsconfig ?? "tsconfig.json");
    if (!fs.existsSync(requestedConfig)) return [];
    const root = fs.realpathSync(requestedRoot);
    const configFile = fs.realpathSync(requestedConfig);
    const require = createRequire(path.join(root, "package.json"));
    let front: string;
    try {
        front = require.resolve("@finesoft/front");
    } catch {
        return [];
    }
    const c: typeof ts = require("typescript");
    const input = fs.readFileSync(configFile, "utf8");
    const parsed = c.parseConfigFileTextToJson(configFile, input);
    if (parsed.error) throw Error(c.flattenDiagnosticMessageText(parsed.error.messageText, "\n"));
    const output = path.join(root, ".finesoft/front.d.ts");
    const resolved = c.parseJsonConfigFileContent(
        parsed.config,
        c.sys,
        path.dirname(configFile),
        undefined,
        configFile,
    );
    const configBase = resolved.options.baseUrl ?? path.dirname(configFile);
    const alias = relative(configBase, output);
    const existing = resolved.options.paths?.["@finesoft/front"];
    // A deliberate source alias belongs to the user (and is used by framework development).
    if (existing && !(existing.length === 1 && path.resolve(configBase, existing[0]) === output))
        return [];
    const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
    if (pkg.name === "@finesoft/front") return [];
    const deps = { ...pkg.dependencies, ...pkg.devDependencies, ...pkg.peerDependencies };
    const installed = (name: string) => {
        if (!deps[name]) return false;
        try {
            require.resolve(`${name}/package.json`);
            return true;
        } catch {
            try {
                require.resolve(name);
                return true;
            } catch {
                return false;
            }
        }
    };
    const entry = (name: string) =>
        JSON.stringify(
            relative(path.dirname(output), path.join(path.dirname(front), `${name}.mjs`)),
        );
    const renderers = ["react", "vue", "svelte"].filter(installed);
    const lines = [
        "// Generated by @finesoft/front. Re-run finesoft-types after changing dependencies.",
        `export * from ${entry("portable")};`,
        `export { generateFrontTypes, generateControllerTypes } from ${entry("typegen")};`,
        `export type { FrontTypeOptions, ControllerTypeOptions, ControllerTypeResult } from ${entry("typegen")};`,
    ];
    if (installed("@types/node") || installed("@hono/node-server"))
        lines.push(`export * from ${entry("node")};`);
    if (installed("vite") || installed("vite-plus")) lines.push(`export * from ${entry("vite")};`);
    if (renderers.length) {
        lines.push(`import type { NativeAPI } from ${entry("native-contract")};`);
        for (const name of renderers) lines.push(`import type * as ${name} from ${entry(name)};`);
        lines.push(
            `export interface NativeBindings { ${renderers.map((name) => `${name}: typeof ${name};`).join(" ")} }`,
            "export type Renderer = keyof NativeBindings;",
            `interface NativeViewTypes { ${renderers.map((name) => `${name}: ${name}.NativeView;`).join(" ")} }`,
            "export type NativeView<R extends Renderer> = NativeViewTypes[R];",
            "export type NativeViews<R extends Renderer> = Readonly<Record<string, NativeView<R>>>;",
            'export declare const Outlet: NativeAPI<NativeBindings>["Outlet"];',
            'export declare const useSnapshot: NativeAPI<NativeBindings>["useSnapshot"];',
        );
    }
    const changed: string[] = [];
    const write = (file: string, content: string) => {
        assertEditablePath(root, file);
        if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === content) return;
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, content);
        changed.push(file);
    };
    write(output, lines.join("\n") + "\n");
    if (!existing) {
        const source = c.parseJsonText(configFile, input);
        const object = source.statements[0]?.expression;
        if (!object || !c.isObjectLiteralExpression(object))
            throw Error(`Invalid tsconfig: ${configFile}`);
        const property = (value: ts.ObjectLiteralExpression, name: string) =>
            value.properties.find(
                (item): item is ts.PropertyAssignment =>
                    c.isPropertyAssignment(item) &&
                    (c.isStringLiteral(item.name) || c.isIdentifier(item.name)) &&
                    item.name.text === name,
            );
        const compilerOptions = property(object, "compilerOptions");
        const compilerObject =
            compilerOptions && c.isObjectLiteralExpression(compilerOptions.initializer)
                ? compilerOptions.initializer
                : undefined;
        const paths = compilerObject && property(compilerObject, "paths");
        const pathsObject =
            paths && c.isObjectLiteralExpression(paths.initializer) ? paths.initializer : undefined;
        const target = pathsObject ?? compilerObject ?? object;
        const inherited = !pathsObject && resolved.options.paths ? resolved.options.paths : {};
        const pathsBase =
            resolved.options.baseUrl ??
            (typeof resolved.options.pathsBasePath === "string"
                ? resolved.options.pathsBasePath
                : path.dirname(configFile));
        const mapping = Object.entries({ ...inherited, "@finesoft/front": [alias] })
            .map(
                ([name, values]) =>
                    `${JSON.stringify(name)}: ${JSON.stringify(name === "@finesoft/front" ? values : values.map((value) => relative(configBase, path.resolve(pathsBase, value))))}`,
            )
            .join(",\n");
        const addition = pathsObject
            ? mapping
            : compilerObject
              ? `"paths": { ${mapping} }`
              : `"compilerOptions": { "paths": { ${mapping} } }`;
        const last = target.properties.at(-1);
        const position = last?.end ?? target.getStart(source) + 1;
        const insertion = last ? `,\n${addition}` : `\n${addition}\n`;
        // Insert before an existing trailing comma/comment, retaining JSONC and every other option.
        write(configFile, input.slice(0, position) + insertion + input.slice(position));
    }
    return changed;
}
